### ISSUE TITLE
make depends

### ISSUE THREAD

**Issue by BUPT1226** [ReliaQualAssociates/ramstk#1126]
windows system use order  "make depends"  can produce error：process_begin: CreateProcess(NULL, which poetry, ...) failed........Error 2

**Comment by weibullguy** [comment]
I don't have access to a Windows machine to be able to troubleshoot.  But, that is an error raised by GNU make, I believe.  If you can't find a version of make for Windows that works, you can try to run the make depends target commands manually.  These would be:

`python -m pip install -U pip wheel`
`poetry install --no-root`

**Comment by BUPT1226** [comment]
First of all, thank you for your answer. I did as you said, but another thorny problem has arisen.When I type the following sentence：”poetry install --no-root“
The following results appear：
Package operations: 1 install, 0 updates, 0 removals
  • Installing pygobject (3.42.2)
  CalledProcessError
   ........
 Failed to build PyGObject
 ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects

How can I solve this problem？

**Comment by weibullguy** [comment]
You have to install pygobject not using poetry.  The instructions are [here](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows).

**Comment by BUPT1226** [comment]
Sorry to bother you again , now I'm running on Ubuntu(WSL) . I have installed the ramstk ,but when I run the following order :
$ramstk 
The result is ：
(ramstk-py3.8) messi@LAPTOP-UHPEPM3A:/home/ramstk-0.19.0$ ramstk
/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/analyses/dormancy.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  DORMANT_HR_MULT = np.array(
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/bin/ramstk", line 8, in <module>
    sys.exit(the_one_ring())
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/__main__.py", line 322, in the_one_ring
    site_configuration = do_read_site_configuration()
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/__main__.py", line 258, in do_read_site_configuration
    do_first_run(_configuration)
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/__main__.py", line 107, in do_first_run
    _dialog = RAMSTKDatabaseSelect(
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/views/gtk3/widgets/dialog.py", line 76, in __init__
    super().__init__(dlgtitle, **kwargs)
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/views/gtk3/widgets/dialog.py", line 53, in __init__
    super().__init__()
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 577, in __init__
    self._init(*args, **new_kwargs)
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
  File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
(ramstk-py3.8) messi@LAPTOP-UHPEPM3A:/home/ramstk-0.19.0$

What can i do to solve this problem?

**Comment by BUPT1226** [comment]
Sorry to bother you again , now I'm running on Ubuntu(WSL) . I have installed the ramstk ,but when I run the following order :
$ramstk
The result is ：
```
(ramstk-py3.8) messi@LAPTOP:/home/ramstk-0.19.0$ ramstk
/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/analyses/dormancy.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
DORMANT_HR_MULT = np.array(
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/bin/ramstk", line 8, in
sys.exit(the_one_ring())
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/main.py", line 322, in the_one_ring
site_configuration = do_read_site_configuration()
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/main.py", line 258, in do_read_site_configuration
do_first_run(_configuration)
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/main.py", line 107, in do_first_run
_dialog = RAMSTKDatabaseSelect(
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/views/gtk3/widgets/dialog.py", line 76, in init
super().init(dlgtitle, **kwargs)
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/ramstk/views/gtk3/widgets/dialog.py", line 53, in init
super().init()
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 577, in init
self._init(*args, **new_kwargs)
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/gi/overrides/init.py", line 319, in new_init
return super_init_func(self, **new_kwargs)
File "/home/messi/.cache/pypoetry/virtualenvs/ramstk-nmzo7p3X-py3.8/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 519, in init
raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
(ramstk-py3.8) messi@LAPTOP:/home/ramstk-0.19.0$
```

What can i do to solve this problem?

**Comment by weibullguy** [comment]
This is a problem with Gtk not finding a display.  Are you executing the command from a terminal emulator or are you at the command line?

**Comment by BUPT1226** [comment]
I think it should be the command line .

**Comment by weibullguy** [comment]
You need to be running a graphical interface, not the command line.  Once you're running a graphical interface, launch a terminal emulator and execute the ramstk command.

**Comment by BUPT1226** [comment]
Now I am running on Linux system by using virtual machine . And my linux syetem is centOS7 .When I execute the following order
$make depends
The error arise . That is, the **pycairo** package download failed.I search the solution to this error online but I did't find out .Meanwhile I read the instrutions which you mentioned eariler ,but it doesn't have the solution of centOS. The instructions are [here](https://pycairo.readthedocs.io/en/latest/getting_started.html).
Do you know the solution of the centOS7 ?

**Comment by weibullguy** [comment]
For CentOS, try the Fedora instructions.  However, none of the problems you're reporting have anything to do with ramstk.  That being the case, I'm closing this issue.

**Comment by BUPT1226** [comment]
Ok，thank you very much.
