### ISSUE TITLE
New RAMSTK Program Database Not Opening; Must Restart RAMSTK

### ISSUE THREAD

**Issue by weibullguy** [ReliaQualAssociates/ramstk#139]
### Expected Behavior ###

As an analyst, I want a newly created RAMSTK Program database to open as soon as it is created so that I don't have to close and restart RAMSTK.

### Actual Behavior (NOT required for Enhancement type issues.) ###

When creating a new RAMSTK database, the following error is received:

    Traceback (most recent call last):
      File "/home/arowland/.local/lib/python2.7/site-packages/rtk/gui/gtk/assistants/CreateProject.py", line 49, in __init__
        self._request_create_sqlite3_project()
      File "/home/arowland/.local/lib/python2.7/site-packages/rtk/gui/gtk/assistants/CreateProject.py", line 96, in _request_create_sqlite3_project
        self._mdcRAMSTK.request_do_create_program()
      File "/home/arowland/.local/lib/python2.7/site-packages/rtk/RAMSTK.py", line 702, in request_do_create_program
        self.request_open_program()
    AttributeError: 'RAMSTK' object has no attribute 'request_open_program'

The database is properly created and can be loaded after the RAMSTK application is closed and re-opened.

### Steps to Reproduce the Problem (NOT required for Enhancement type issues.) ###

1. Open RAMSTK
2. Create a new RAMSTK Program database

### Operating Environment (NOT required for QA type issues.) ###

* RAMSTK Version: 1.0.0.dev1
* Operating System: Linux
* OS Distribution (if Linux): Scientific
* OS Version: 
* Hardware: ASUS laptop with Core i7 processor
* Required Software Versions:
  * Python == 2.7.5
  * defusedxml == 0.5.0
  * lifelines == 0.14.6
  * lxml == 4.2.3
  * matplotlib == 1.4.3
  * numpy == 1.14.5
  * pandas == 0.23.3
  * pypubsub == 3.3.0
  * scipy == 1.1.0
  * sortedcontainers == 1.5.9
  * sqlalchemy == 1.2.10
  * sqlalchemy_utils == 0.33.3
  * statsmodels == 0.9.0
  * treelib == 1.5.3
  * xlrd == 1.1.0
  * xlwt == 1.3.0

**Comment by weibullguy** [comment]
Fixed in commit 983e9dadf8af52f000eb36f75cecbd09a1adda56
